name: Node.js Docker CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t tarunmetia2025/aws-node-docker  .
      - name: Publish Image to docker hub
        run: docker push tarunmetia2025/aws-node-docker:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull tarunmetia2025/aws-node-docker:latest 
      - name: Delete old container
        run: docker rm -f nodejs-app-container  with .env file
      - name: Run Docker Container
        run:  docker run -d --env-file /home/ubuntu/node-runner-etc/.env -p 4000:4000 --name nodejs-app-container tarunmetia2025/aws-node-docker:latest
